title: Blog - Tuannm
encoding: utf-8
highlighter: rouge
description:
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://blog.tuannm.com"
production_url: https://blog.tuannm.com
site-twitter: tuannm993 #if your site has a twitter account, enter it here

# Author Settings
author: Nguyen Manh Tuan # add your name
author-link: "https://tuannm.com"
author-img: tuannm93.jpg # add your photo
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
social-twitter: tuannm993 # add your Twitter handle
social-facebook: tuannm93 # add your Facebook handle
social-github: tuannm93 # add your Github handle
social-linkedin: tuannm93 # add your Linkedin handle
social-email: tuannm.work@gmail.com # add your Email address

# Disqus
comments: true
discus-identifier: tuannm93 # add your discus identifier

# Tracker
analytics: UA-85292248-3 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
